FROM node:22.9.0-alpine

WORKDIR /opt/

COPY package.json /opt/

RUN npm install

COPY . .

RUN npm test

# pongo este puerto para diferenciarlo con el de front. 
EXPOSE 4000  

CMD ["npm", "run", "start"]